require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PasarsController do

  # This should return the minimal set of attributes required to create a valid
  # Pasar. As you add validations to Pasar, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "nama" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PasarsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all pasars as @pasars" do
      pasar = Pasar.create! valid_attributes
      get :index, {}, valid_session
      assigns(:pasars).should eq([pasar])
    end
  end

  describe "GET show" do
    it "assigns the requested pasar as @pasar" do
      pasar = Pasar.create! valid_attributes
      get :show, {:id => pasar.to_param}, valid_session
      assigns(:pasar).should eq(pasar)
    end
  end

  describe "GET new" do
    it "assigns a new pasar as @pasar" do
      get :new, {}, valid_session
      assigns(:pasar).should be_a_new(Pasar)
    end
  end

  describe "GET edit" do
    it "assigns the requested pasar as @pasar" do
      pasar = Pasar.create! valid_attributes
      get :edit, {:id => pasar.to_param}, valid_session
      assigns(:pasar).should eq(pasar)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Pasar" do
        expect {
          post :create, {:pasar => valid_attributes}, valid_session
        }.to change(Pasar, :count).by(1)
      end

      it "assigns a newly created pasar as @pasar" do
        post :create, {:pasar => valid_attributes}, valid_session
        assigns(:pasar).should be_a(Pasar)
        assigns(:pasar).should be_persisted
      end

      it "redirects to the created pasar" do
        post :create, {:pasar => valid_attributes}, valid_session
        response.should redirect_to(Pasar.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pasar as @pasar" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pasar.any_instance.stub(:save).and_return(false)
        post :create, {:pasar => { "nama" => "invalid value" }}, valid_session
        assigns(:pasar).should be_a_new(Pasar)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pasar.any_instance.stub(:save).and_return(false)
        post :create, {:pasar => { "nama" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested pasar" do
        pasar = Pasar.create! valid_attributes
        # Assuming there are no other pasars in the database, this
        # specifies that the Pasar created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Pasar.any_instance.should_receive(:update_attributes).with({ "nama" => "MyString" })
        put :update, {:id => pasar.to_param, :pasar => { "nama" => "MyString" }}, valid_session
      end

      it "assigns the requested pasar as @pasar" do
        pasar = Pasar.create! valid_attributes
        put :update, {:id => pasar.to_param, :pasar => valid_attributes}, valid_session
        assigns(:pasar).should eq(pasar)
      end

      it "redirects to the pasar" do
        pasar = Pasar.create! valid_attributes
        put :update, {:id => pasar.to_param, :pasar => valid_attributes}, valid_session
        response.should redirect_to(pasar)
      end
    end

    describe "with invalid params" do
      it "assigns the pasar as @pasar" do
        pasar = Pasar.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pasar.any_instance.stub(:save).and_return(false)
        put :update, {:id => pasar.to_param, :pasar => { "nama" => "invalid value" }}, valid_session
        assigns(:pasar).should eq(pasar)
      end

      it "re-renders the 'edit' template" do
        pasar = Pasar.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pasar.any_instance.stub(:save).and_return(false)
        put :update, {:id => pasar.to_param, :pasar => { "nama" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pasar" do
      pasar = Pasar.create! valid_attributes
      expect {
        delete :destroy, {:id => pasar.to_param}, valid_session
      }.to change(Pasar, :count).by(-1)
    end

    it "redirects to the pasars list" do
      pasar = Pasar.create! valid_attributes
      delete :destroy, {:id => pasar.to_param}, valid_session
      response.should redirect_to(pasars_url)
    end
  end

end
