require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TbPeriodsController do

  # This should return the minimal set of attributes required to create a valid
  # TbPeriod. As you add validations to TbPeriod, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "period" => "2013-07-12 13:41:54" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TbPeriodsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all tb_periods as @tb_periods" do
      tb_period = TbPeriod.create! valid_attributes
      get :index, {}, valid_session
      assigns(:tb_periods).should eq([tb_period])
    end
  end

  describe "GET show" do
    it "assigns the requested tb_period as @tb_period" do
      tb_period = TbPeriod.create! valid_attributes
      get :show, {:id => tb_period.to_param}, valid_session
      assigns(:tb_period).should eq(tb_period)
    end
  end

  describe "GET new" do
    it "assigns a new tb_period as @tb_period" do
      get :new, {}, valid_session
      assigns(:tb_period).should be_a_new(TbPeriod)
    end
  end

  describe "GET edit" do
    it "assigns the requested tb_period as @tb_period" do
      tb_period = TbPeriod.create! valid_attributes
      get :edit, {:id => tb_period.to_param}, valid_session
      assigns(:tb_period).should eq(tb_period)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TbPeriod" do
        expect {
          post :create, {:tb_period => valid_attributes}, valid_session
        }.to change(TbPeriod, :count).by(1)
      end

      it "assigns a newly created tb_period as @tb_period" do
        post :create, {:tb_period => valid_attributes}, valid_session
        assigns(:tb_period).should be_a(TbPeriod)
        assigns(:tb_period).should be_persisted
      end

      it "redirects to the created tb_period" do
        post :create, {:tb_period => valid_attributes}, valid_session
        response.should redirect_to(TbPeriod.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tb_period as @tb_period" do
        # Trigger the behavior that occurs when invalid params are submitted
        TbPeriod.any_instance.stub(:save).and_return(false)
        post :create, {:tb_period => { "period" => "invalid value" }}, valid_session
        assigns(:tb_period).should be_a_new(TbPeriod)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TbPeriod.any_instance.stub(:save).and_return(false)
        post :create, {:tb_period => { "period" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tb_period" do
        tb_period = TbPeriod.create! valid_attributes
        # Assuming there are no other tb_periods in the database, this
        # specifies that the TbPeriod created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TbPeriod.any_instance.should_receive(:update_attributes).with({ "period" => "2013-07-12 13:41:54" })
        put :update, {:id => tb_period.to_param, :tb_period => { "period" => "2013-07-12 13:41:54" }}, valid_session
      end

      it "assigns the requested tb_period as @tb_period" do
        tb_period = TbPeriod.create! valid_attributes
        put :update, {:id => tb_period.to_param, :tb_period => valid_attributes}, valid_session
        assigns(:tb_period).should eq(tb_period)
      end

      it "redirects to the tb_period" do
        tb_period = TbPeriod.create! valid_attributes
        put :update, {:id => tb_period.to_param, :tb_period => valid_attributes}, valid_session
        response.should redirect_to(tb_period)
      end
    end

    describe "with invalid params" do
      it "assigns the tb_period as @tb_period" do
        tb_period = TbPeriod.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TbPeriod.any_instance.stub(:save).and_return(false)
        put :update, {:id => tb_period.to_param, :tb_period => { "period" => "invalid value" }}, valid_session
        assigns(:tb_period).should eq(tb_period)
      end

      it "re-renders the 'edit' template" do
        tb_period = TbPeriod.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TbPeriod.any_instance.stub(:save).and_return(false)
        put :update, {:id => tb_period.to_param, :tb_period => { "period" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tb_period" do
      tb_period = TbPeriod.create! valid_attributes
      expect {
        delete :destroy, {:id => tb_period.to_param}, valid_session
      }.to change(TbPeriod, :count).by(-1)
    end

    it "redirects to the tb_periods list" do
      tb_period = TbPeriod.create! valid_attributes
      delete :destroy, {:id => tb_period.to_param}, valid_session
      response.should redirect_to(tb_periods_url)
    end
  end

end
